version: '3.8'
services:
  mocks:
    restart: unless-stopped
    build: ./mocks
    command: npm run start
    environment:
      DPI_HOST: ${DPI_HOST}
    ports:
      - ${MOCK_PORT}:${MOCK_PORT}
    networks: 
      - backend
  sa-mock:
    restart: unless-stopped
    build: ./move-sakarkiv-mock
    command: npm run start
    environment:
      IP_URL: ${IP_URL}
    ports:
      - ${SA_MOCK_PORT}:${SA_MOCK_PORT}
    networks: 
      - backend
    depends_on:
      - ip
  wiremock:
    restart: unless-stopped
    build: ./Wiremock
    ports:
      - ${WIREMOCK_PORT}:${WIREMOCK_PORT}
    networks: 
      - backend
  dpimock:
    restart: unless-stopped
    build: ./dpimock
    command:  cd ./dpimock && ./mvnw install dockerfile:build
    ports:
      - ${DPI_PORT}:8080
    networks: 
      - backend      
  ip:
    restart: unless-stopped
    build: ./ip
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_OPTS: -Xmx2g
    ports:
      - ${IP_PORT}:9093
    networks: 
      - backend
networks:
  backend:
    driver: "bridge"