FROM difi/integrasjonspunkt:development

COPY integrasjonspunkt-local.properties /var/lib/difi
COPY integrasjonspunkt-local.properties /var/lib/difi
COPY mock-truststore.jks /var/lib/difi
COPY kontaktinfo-client.pem /var/lib/difi
COPY mock.jks /var/lib/difi
