FROM digdir/integrasjonspunkt:latest

COPY integrasjonspunkt-local.properties /opt/integrasjonspunkt
COPY application.properties /opt/integrasjonspunkt
COPY eformidling-root-intermediate.jks /opt/integrasjonspunkt
COPY altinn-810074582.jks /opt/integrasjonspunkt

